### ISSUE TITLE
Repository: Is the source code for this software available at the repository url?

### ISSUE THREAD

**Issue by ltetrel** [neurolibre/neurolibre-reviews#8]

**Comment by roboneuro** [comment]
Downloading of the repository (to analyze the language) for issue #8 failed with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-364ded062842/lib/whedon/processor.rb:27:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-364ded062842/lib/whedon.rb:375:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-364ded062842/lib/whedon.rb:375:in `download'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-364ded062842/bin/whedon:38:in `download'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-364ded062842/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by roboneuro** [comment]
Downloading of the repository (to check the bibtex) failed for issue #8 failed with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-364ded062842/lib/whedon/processor.rb:27:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-364ded062842/lib/whedon.rb:375:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-364ded062842/lib/whedon.rb:375:in `download'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-364ded062842/bin/whedon:38:in `download'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-364ded062842/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'
